create database capstone;
 
-- Inner Join for Order Details
--  o Join orders, order_items, and products to display detailed line items.
select o.*,oi.*,p.* from capstone.orders o 
join capstone.order_items oi 
on o.Order_id=oi.Order_id
join capstone.products p
on oi.Product_id=p.Product_id;
 
-- Write a query to group sales (total_price) by each store_id.
select o.Store_id,sum(oi.Total_Price) as sales from capstone.order_items oi
join capstone.orders as o
on o.Order_id=oi.Order_id
group by o.Store_id;
 
-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity
select p.Product_id,p.Product_name,count(oi.Quantity) from capstone.order_items oi
join capstone.products p
on p.Product_id=oi.Product_id
group by p.Product_id,p.Product_name,oi.Quantity
order by Quantity  desc
limit 5;

--  For each customer, return total orders placed, total items purchased, and total revenue.
select o.Customer_id,count(oi.Order_id) as order_placed,sum(oi.Item_id) as item_purchased,sum(oi.Total_Price) as total_revenue
from capstone.order_items oi
join capstone.orders o
on o.Order_id=oi.Order_id
group by Customer_id;

--  o Write a query to classify customers into spending brackets (e.g., low, medium, high).
SELECT o.Customer_id,SUM(oi.Total_Price) AS spending,
    CASE
        WHEN SUM(oi.Total_Price) > 1000 THEN 'High'
        WHEN SUM(oi.Total_Price) BETWEEN 500 AND 1000 THEN 'Medium'
        ELSE 'Low'
    END AS spending_bracket
FROM capstone.order_items oi
JOIN capstone.orders o
    ON o.Order_ID = oi.Order_ID
GROUP BY o.Customer_id;
 
-- Analyze total revenue generated by each staff member based on their handled orders.
select s.Staff_id,s.Name,sum(oi.Total_Price) as Total_Revenue 
from capstone.staffs s
join capstone.orders o
on s.Staff_id=o.Staff_id
join capstone.order_items oi
on o.Order_id=oi.Order_id
group by s.Staff_id,s.Name
order by Total_Revenue desc;
 
--  Write a query to list products where stock quantity < 10 in any store.
select p.product_id,p.Product_name,s.Store_id,s.Quantity
from capstone.products p
join capstone.stocks s
on s.Product_id=p.Product_id
where s.Quantity<10;